# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_boltdetails.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pitch(object):
    def setupUi(self, Pitch):
        Pitch.setObjectName("Pitch")
        Pitch.resize(339, 304)
        Pitch.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        Pitch.setFont(font)
        self.scrollArea = QtWidgets.QScrollArea(Pitch)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 321, 286))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 284))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 8, 0, 1, 6)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 1)
        self.lbl_mem = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem.setFont(font)
        self.lbl_mem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem.setObjectName("lbl_mem")
        self.gridLayout_2.addWidget(self.lbl_mem, 1, 0, 1, 1)
        self.lbl_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_1.setFont(font)
        self.lbl_1.setObjectName("lbl_1")
        self.gridLayout_2.addWidget(self.lbl_1, 1, 2, 1, 1)
        self.txt_no_of_rows_bolts = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.txt_no_of_rows_bolts.setFont(font)
        self.txt_no_of_rows_bolts.setReadOnly(True)
        self.txt_no_of_rows_bolts.setObjectName("txt_no_of_rows_bolts")
        self.gridLayout_2.addWidget(self.txt_no_of_rows_bolts, 1, 4, 1, 1)
        self.lbl_mem2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2.setFont(font)
        self.lbl_mem2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2.setObjectName("lbl_mem2")
        self.gridLayout_2.addWidget(self.lbl_mem2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 5, 1, 1)
        self.lbl_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_2.setFont(font)
        self.lbl_2.setObjectName("lbl_2")
        self.gridLayout_2.addWidget(self.lbl_2, 2, 2, 1, 1)
        self.txt_no_of_columns_bolts = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.txt_no_of_columns_bolts.setFont(font)
        self.txt_no_of_columns_bolts.setReadOnly(True)
        self.txt_no_of_columns_bolts.setObjectName("txt_no_of_columns_bolts")
        self.gridLayout_2.addWidget(self.txt_no_of_columns_bolts, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 5, 1, 1)
        self.lbl_mem2_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2_2.setFont(font)
        self.lbl_mem2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2_2.setObjectName("lbl_mem2_2")
        self.gridLayout_2.addWidget(self.lbl_mem2_2, 3, 0, 1, 1)
        self.txt_row_pitch = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.txt_row_pitch.setFont(font)
        self.txt_row_pitch.setReadOnly(True)
        self.txt_row_pitch.setObjectName("txt_row_pitch")
        self.gridLayout_2.addWidget(self.txt_row_pitch, 3, 4, 1, 1)
        self.lbl_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_5.setFont(font)
        self.lbl_5.setObjectName("lbl_5")
        self.gridLayout_2.addWidget(self.lbl_5, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 5, 1, 1)
        self.lbl_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_4.setFont(font)
        self.lbl_4.setObjectName("lbl_4")
        self.gridLayout_2.addWidget(self.lbl_4, 3, 2, 1, 1)
        self.lbl_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_7.setFont(font)
        self.lbl_7.setObjectName("lbl_7")
        self.gridLayout_2.addWidget(self.lbl_7, 6, 2, 1, 1)
        self.txt_column_pitch = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.txt_column_pitch.setFont(font)
        self.txt_column_pitch.setReadOnly(True)
        self.txt_column_pitch.setObjectName("txt_column_pitch")
        self.gridLayout_2.addWidget(self.txt_column_pitch, 4, 4, 1, 1)
        self.lbl_mem2_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2_3.setFont(font)
        self.lbl_mem2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2_3.setObjectName("lbl_mem2_3")
        self.gridLayout_2.addWidget(self.lbl_mem2_3, 4, 0, 1, 1)
        self.txt_bolt_qty = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.txt_bolt_qty.setFont(font)
        self.txt_bolt_qty.setReadOnly(True)
        self.txt_bolt_qty.setObjectName("txt_bolt_qty")
        self.gridLayout_2.addWidget(self.txt_bolt_qty, 6, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 6, 5, 1, 1)
        self.lbl_mem2_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2_4.setFont(font)
        self.lbl_mem2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2_4.setObjectName("lbl_mem2_4")
        self.gridLayout_2.addWidget(self.lbl_mem2_4, 6, 0, 1, 1)
        self.lbl_mem2_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2_5.setFont(font)
        self.lbl_mem2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2_5.setObjectName("lbl_mem2_5")
        self.gridLayout_2.addWidget(self.lbl_mem2_5, 7, 0, 1, 1)
        self.lbl_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_8.setFont(font)
        self.lbl_8.setObjectName("lbl_8")
        self.gridLayout_2.addWidget(self.lbl_8, 7, 2, 1, 1)
        self.txt_req_bolt = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.txt_req_bolt.setFont(font)
        self.txt_req_bolt.setReadOnly(True)
        self.txt_req_bolt.setObjectName("txt_req_bolt")
        self.gridLayout_2.addWidget(self.txt_req_bolt, 7, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 7, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 8, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 0, 3, 8, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Pitch)
        QtCore.QMetaObject.connectSlotsByName(Pitch)

    def retranslateUi(self, Pitch):
        _translate = QtCore.QCoreApplication.translate
        Pitch.setWindowTitle(_translate("Pitch", "Bolt Detail"))
        self.textEdit.setHtml(_translate("Pitch", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Note: Row_Pitch is the Pitch perpendicular to the Tension lIne and Column Pitch is the Pitch along the Tension line. </p></body></html>"))
        self.label_2.setText(_translate("Pitch", "Designation"))
        self.label.setText(_translate("Pitch", "Sr. No."))
        self.label_5.setText(_translate("Pitch", "Pitch (mm)"))
        self.lbl_mem.setText(_translate("Pitch", "1"))
        self.lbl_1.setText(_translate("Pitch", "No of Bolt Rows"))
        self.lbl_mem2.setText(_translate("Pitch", "2"))
        self.lbl_2.setText(_translate("Pitch", "No of Bolt Columns"))
        self.lbl_mem2_2.setText(_translate("Pitch", "3"))
        self.lbl_5.setText(_translate("Pitch", "Column_Pitch"))
        self.lbl_4.setText(_translate("Pitch", "Row_Pitch"))
        self.lbl_7.setText(_translate("Pitch", "Bolt_Qty"))
        self.lbl_mem2_3.setText(_translate("Pitch", "4"))
        self.lbl_mem2_4.setText(_translate("Pitch", "5"))
        self.lbl_mem2_5.setText(_translate("Pitch", "6"))
        self.lbl_8.setText(_translate("Pitch", "Required Bolt"))
from . import icons_rc
