# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_weld.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Weld(object):
    def setupUi(self, Weld):
        Weld.setObjectName("Weld")
        Weld.resize(332, 223)
        Weld.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        Weld.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Weld)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Weld)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 312, 203))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 4, 0, 1, 6)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 0, 3, 4, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 4, 1)
        self.lbl_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_3.setFont(font)
        self.lbl_3.setObjectName("lbl_3")
        self.gridLayout_2.addWidget(self.lbl_3, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 1)
        self.lbl_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_1.setFont(font)
        self.lbl_1.setObjectName("lbl_1")
        self.gridLayout_2.addWidget(self.lbl_1, 1, 2, 1, 1)
        self.txt_weldsize = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.txt_weldsize.setFont(font)
        self.txt_weldsize.setReadOnly(True)
        self.txt_weldsize.setObjectName("txt_weldsize")
        self.gridLayout_2.addWidget(self.txt_weldsize, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 5, 1, 1)
        self.weld_length1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.weld_length1.setFont(font)
        self.weld_length1.setReadOnly(True)
        self.weld_length1.setObjectName("weld_length1")
        self.gridLayout_2.addWidget(self.weld_length1, 2, 4, 1, 1)
        self.lbl_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_2.setFont(font)
        self.lbl_2.setObjectName("lbl_2")
        self.gridLayout_2.addWidget(self.lbl_2, 2, 2, 1, 1)
        self.lbl_mem2_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2_2.setFont(font)
        self.lbl_mem2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2_2.setObjectName("lbl_mem2_2")
        self.gridLayout_2.addWidget(self.lbl_mem2_2, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 5, 1, 1)
        self.lbl_mem = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem.setFont(font)
        self.lbl_mem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem.setObjectName("lbl_mem")
        self.gridLayout_2.addWidget(self.lbl_mem, 1, 0, 1, 1)
        self.lbl_mem2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_mem2.setFont(font)
        self.lbl_mem2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mem2.setObjectName("lbl_mem2")
        self.gridLayout_2.addWidget(self.lbl_mem2, 2, 0, 1, 1)
        self.weld_length2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.weld_length2.setFont(font)
        self.weld_length2.setReadOnly(True)
        self.weld_length2.setObjectName("weld_length2")
        self.gridLayout_2.addWidget(self.weld_length2, 3, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 5, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Weld)
        QtCore.QMetaObject.connectSlotsByName(Weld)

    def retranslateUi(self, Weld):
        _translate = QtCore.QCoreApplication.translate
        Weld.setWindowTitle(_translate("Weld", "Weld Details"))
        self.textEdit.setHtml(_translate("Weld", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Note:</span> Length L1 is the total length of weld along the Tension line and Length L2 is the total length of weld perpendicular to Tension.</p></body></html>"))
        self.label.setText(_translate("Weld", "Sr. No."))
        self.label_2.setText(_translate("Weld", "Designation"))
        self.lbl_3.setText(_translate("Weld", "Length L2"))
        self.label_5.setText(_translate("Weld", "Unit (mm)"))
        self.lbl_1.setText(_translate("Weld", "Weld Size"))
        self.lbl_2.setText(_translate("Weld", "Length L1"))
        self.lbl_mem2_2.setText(_translate("Weld", "3"))
        self.lbl_mem.setText(_translate("Weld", "1"))
        self.lbl_mem2.setText(_translate("Weld", "2"))
from . import icons_rc
